apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-service-api-config
data:
  APP_NAME: "WTP-TIMESHEET-SERVICE"
  ALLOW_ORIGINS: "http://localhost,http://localhost:8000"
  ALLOW_ORIGIN_REGEX: "https://.*\\.regnify\\.com|https://.*\\.azurestaticapps\\.net|https://.*\\.netlify\\.app"
  DOC_URL: "/docs"
  REDOC_URL: "/redoc"
  DB_USER: "wtp-payments"
  DB_PASSWORD: "WTPPASSWORD"
  DB_HOST: "payments-db"
  DB_NAME: "wtp-payments-db"
  DB_PORT: "5432"
  
  OPENAPI_URL: "/openapi.json"
  DISPLAY_SCOPES_IN_DOCUMENTATION: "True"
  
  # * This should only be used for development on your local machine.
  # * Mount a volume on the server to reference these files.
  KEYFILE: "/usr/src/payments-mgt-api/hypercorn/key.pem"
  CERTFILE: "/usr/src/payments-mgt-api/hypercorn/cert.pem"

  TCP_PORT: "8500"
  SSL_PORT: "8501"
  SHOULD_RELOAD: "True"
  MAX_WORKERS: "1"
  USE_SSL: "True"
  USE_TCP: "True"


  #section for external urls without the trailing forward slash where id is needed
  TOKEN_URL: "http://172.19.0.1:5000/token"
  GET_CURRENT_USER: "http://172.19.0.1:5000/user"
  GET_TASK_URL: "http://172.19.0.1:5000/task"

  GET_TIMESHEETS_URL: "http://timesheets-service:8100/timesheets"
  GET_TIMESHEETS_BY_TASK_ID_URL: "http://timesheets-service:5000/timesheets/task"